"""add location table

Revision ID: 07215d056f8b
Revises: 4b8aedd66c58
Create Date: 2023-06-28 21:39:47.172728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07215d056f8b'
down_revision = '4b8aedd66c58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
