"""Add trip_locations table

Revision ID: 1b5a2580d3df
Revises: 4d5660e280a6
Create Date: 2023-07-01 17:12:46.526123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5a2580d3df'
down_revision = '4d5660e280a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_locations',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_trip_locations_location_id_locations')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_locations_trip_id_trips')),
    sa.PrimaryKeyConstraint('trip_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_locations')
    # ### end Alembic commands ###
