"""Add user_trip Association Table

Revision ID: 4d5660e280a6
Revises: baffb19a5f9d
Create Date: 2023-07-01 14:31:35.305255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5660e280a6'
down_revision = 'baffb19a5f9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_trips',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_user_trips_trip_id_trips')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_trips_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_trips')
    # ### end Alembic commands ###
