"""Fix models

Revision ID: 8284de79994e
Revises: 1b5a2580d3df
Create Date: 2023-07-01 17:20:30.311356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8284de79994e'
down_revision = '1b5a2580d3df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
